# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mlsdmitry/Documents/minecraft_engines/cserver/cserver_source/lib/RakNet/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mlsdmitry/Documents/minecraft_engines/cserver/cserver_source/lib/RakNet/CmakeIncludes/CmakeMacros.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mlsdmitry/Documents/minecraft_engines/cserver/cserver_source/lib/RakNet/CmakeIncludes/FindMacros.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mlsdmitry/Documents/minecraft_engines/cserver/cserver_source/lib/RakNet/Lib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mlsdmitry/Documents/minecraft_engines/cserver/cserver_source/lib/RakNet/Lib/DLL/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mlsdmitry/Documents/minecraft_engines/cserver/cserver_source/lib/RakNet/Lib/LibStatic/CMakeLists.txt))

/Users/mlsdmitry/Documents/minecraft_engines/cserver/cserver_source/Xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -H/Users/mlsdmitry/Documents/minecraft_engines/cserver/cserver_source -B/Users/mlsdmitry/Documents/minecraft_engines/cserver/cserver_source/Xcode
